ALTER TABLE salas
    ADD COLUMN IF NOT EXISTS ano_inicio INTEGER,
    ADD COLUMN IF NOT EXISTS ano_fim INTEGER,
    ADD COLUMN IF NOT EXISTS nota_minima NUMERIC(3,1),
    ADD COLUMN IF NOT EXISTS diretor VARCHAR(255);

ALTER TABLE filmes
    ADD COLUMN IF NOT EXISTS diretor VARCHAR(255);
